name: render
on:
  push:
    branches:
      - main
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: cuchi/jinja2-action@v1.2.0
        with:
          data_file: data.yaml
          data_format: yaml
          template: timeline.template.html
          output_file: timeline.html

      - run: cat timeline.html
      # TODO(saffathasan): publish to gh-deploy branch
      # - run: mkdir publish/
      # - run: mv timeline.template.html publish/timeline.html
      # - name: Deploy 🚀
      #   uses: JamesIves/github-pages-deploy-action@4.1.4
      #   with:
      #     branch: gh-pages # The branch the action should deploy to.
      #     folder: publish/ # The folder the action should deploy.